version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
before_package:
  - cmd: dotnet publish ".\src\GeigerComputerCounter\ComputerGeigerCounter.csproj" -c "Release" -r "win-x64" -f "netcoreapp3.1"
after_build:
- ps: >-
    $buildPath = Resolve-Path ".\src\GeigerComputerCounter\bin\Release\*\*\publish"
    Write-Host "Zipping $buildPath"
    7z a noobot.zip "$buildPath\*"
test: off
artifacts:
- path: geiger-counter.zip
deploy:
- provider: GitHub
  artifact: geiger-counter.zip
  on:
    branch: main