version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: >-
    dotnet restore
    Push-Location "src/Noobot.Console/Configuration/"
    copy "config.default.json" "config.json"
    Pop-Location
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal

before_package:
- cmd: dotnet publish ".\src\Noobot.Console\Noobot.Console.csproj" -c "Release" -r "win-x64" -f "netcoreapp3.1"
after_build:
- ps: >-
    $buildPath = Resolve-Path ".\src\Noobot.Console\bin\Release\*\*\publish"
    Write-Host "Zipping $buildPath"
    7z a noobot.zip "$buildPath\*"
test: off
artifacts:
- path: noobot.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 8t4+xbVlkXA/FY3516ThrMibGxfCT7ZcSwyZw7KNwUlCH08KMPtznY2QphEn1n/z
  artifact: noobot.zip,/.*\.nupkg/
  draft: true
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: ImI1DBI5d+r46a2qVVgGlXjmjQ4uAk57eETmeY30OI3Um8UnYADfQzWXZ4r37Zo6
  skip_symbols: false
  on:
    branch: master